"""empty message

Revision ID: c3be335d8ed8
Revises: a082f3b8efff
Create Date: 2023-12-26 17:49:12.712907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3be335d8ed8'
down_revision = 'a082f3b8efff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('age')
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('age', ['age'], unique=False)

    # ### end Alembic commands ###
